# Generated by Django 4.1.4 on 2022-12-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigIntegerField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
